export enum RootGetters {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
}
export enum RootMutations {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
  ITEM_LISTS = "ITEM_LISTS",
}
export enum RootActions {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  ITEM_LISTS = 'ITEM_LISTS',
}
export enum BagGetters {
  TOTAL_PRICE = "TOTAL_PRICE",
  BAG_ITEM_COUNT = "BAG_ITEM_COUNT",
}
export enum WishlistGetters {
  WISHLIST_ITEM_COUNT = "WISHLIST_ITEM_COUNT",
}