export enum RootGetters {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
}
export enum RootMutations {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
  ITEM_LISTS = "ITEM_LISTS",
  ITEM_COUNT = "ITEM_COUNT",
}
export enum RootActions {
  UPDATE_VERSION = "UPDATE_VERSION",
  BAG_CHECK = "BAG_CHECK",
  ITEM_LISTS = 'ITEM_LISTS',
  ITEM_COUNT = 'ITEM_COUNT',
}
export enum BagMutations {
  ADD_BAG_ITEM = 'ADD_BAG_ITEM',
  REMOVE_BAG_ITEM = 'REMOVE_BAG_ITEM',
}
export enum BagActions {
  ADD_BAG_ITEM = 'ADD_BAG_ITEM',
  REMOVE_BAG_ITEM = 'REMOVE_BAG_ITEM',
}
export enum BagGetters {
  TOTAL_PRICE = "TOTAL_PRICE",
  BAG_ITEM_COUNT = "BAG_ITEM_COUNT",
}
export enum WishlistMutations {
  ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM',
  REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM',
}
export enum WishlistActions {
  ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM',
  REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM',
}
export enum WishlistGetters {
  WISHLIST_ITEM_COUNT = "WISHLIST_ITEM_COUNT",
}